DROP VIEW IF EXISTS popular_event CASCADE;

DROP TRIGGER IF EXISTS trg_increment_view_count ON event_subscription CASCADE;
DROP FUNCTION IF EXISTS update_view_count() CASCADE;

DROP TABLE IF EXISTS notification_log CASCADE;
DROP TABLE IF EXISTS event_subscription CASCADE;
DROP TABLE IF EXISTS category_event CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS venue CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS organizer CASCADE;
DROP TABLE IF EXISTS common_user CASCADE;
DROP TABLE IF EXISTS "admin" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;